# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
        
      - name: Listar Versiones
        run: |          
          java -version
#          liquibase --version
        
      - name: Instalar liquibase
        run: |         
          sudo mkdir -p /liquibase/bin && cd /liquibase
          sudo wget -O /liquibase/liquibase.tar.gz https://github.com/liquibase/liquibase/releases/download/v4.19.0/liquibase-4.19.0.tar.gz
          sudo wget -q -O /liquibase/lpm.zip "https://github.com/liquibase/liquibase-package-manager/releases/download/v0.2.4/lpm-0.2.4-linux.zip"
          sudo tar -xzpf liquibase.tar.gz
          sudo unzip lpm.zip -d bin
          export LIQUIBASE_HOME=/liquibase
          export PATH=/liquibase:$PATH
#          /liquibase/bin/lpm update
#          tar -xvzf liquibase.tar.gz
      - name: Listar Versiones de liquibase
        run: |      
          /liquibase/liquibase --version
          
      - name: Check if Directory Exists
        run: | 
            YEAR=$(date +'%Y')
            MONTH=$(date +'%m')
            FOLDER="/dev/db/changelog/$YEAR/$MONTH"
            if [ ! -d "$FOLDER" ]; then
              echo "Creating folder $FOLDER"
              mkdir -p "$FOLDER"
              touch "$FOLDER/empty_file.txt"
            else
              echo "Folder $FOLDER already exists"
            fi
# sudo mkdir -p /dev/db/chagelog/$(date +"%Y")/$(date +"%m") || touch         

      - name: Copiar changelog base
        run: sudo cp base/db/changelog/changelog.sql dev/db/chagelog/$(date +"%Y")/$(date +"%m")/$(date +"%Y%m%d%H%M%S").sql 

          
